FROM eclipse-temurin:17.0.5_8-jre-focal as builder
WORKDIR extracted
#ADD ../target/libs/*.jar app.jar

ARG JAR_FILE=target/app.jar
ADD ./target/${JAR_FILE} app.jar
RUN java -Djarmode=layertools -jar app.jar extract
#RUN java -Djarmode=tools -jar ../target/ extract --layers --launcher

FROM eclipse-temurin:17.0.5_8-jre-focal
WORKDIR application
COPY --from=builder extracted/dependencies/ ./
COPY --from=builder extracted/spring-boot-loader/ ./
COPY --from=builder extracted/snapshot-dependencies/ ./
COPY --from=builder extracted/application/ ./

EXPOSE 8080

ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
