
services:

  postgres:
    image: postgres:15
    container_name: postgres-resto-i21
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  resto:
    build:
      dockerfile: Dockerfile-optimized
      args:
        JAR_FILE: restaurant-checker-0.0.1-SNAPSHOT.jar
    image: resto-i3
    container_name: resto-app
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - URL_DATASOURCE=postgres
      - CUSTOM_TEST1=émilie
    ports:
      - "8080:8080"
# no command because we use the JarLauncher in the Dockerfile, therefore we pass the application's configuration via environment variables (see above)
#    command: ["java", "-jar", "app.jar", "--spring.profiles.active=local", "--url.datasource=postgres", "--custom.test1=Émilie", "--test.personal.test2=Émilio"]
    depends_on:
      - postgres


volumes:
  postgres_data:

