
create table restaurants
(
    id_restaurants  bigint generated BY DEFAULT as identity
        constraint restaurants_pk
            primary key,
    created_at      timestamp default now() not null,
    updated_at      timestamp default now() not null,
    adresse         varchar,
    url_website     varchar,
    url_reservation varchar
);

alter table restaurants
    owner to myuser;

